SELECT 
  EXTRACT(MONTH FROM SUBMIT_DATE)AS MNT ,
  PRODUCT_ID AS PRODUCT,
  ROUND(AVG(STARS),2) AS avg_stars
FROM REVIEWS
GROUP BY EXTRACT(MONTH FROM SUBMIT_DATE)  , PRODUCT_ID
ORDER BY MNT ASC , PRODUCT ASC ;